elfi-dev/elfi

elfi/bo/acquisition.py, elfi/bo/gpy_model.py, elfi/posteriors.py, tests/unit/bo/test_acquisition.py
Minor fixes to GPyModel and BolfiPosterior
=> Minor fixes

elfi/bo/gpy_model.py, tests/unit/bo/test_gpy_model.py
Previous implementation of GPyModel caused the kernel parameters to be optimized iteratively, which led to issues with consistency of model fitting (eg. order of observations had a big effect).
The new version uses a fresh kernel and re-fits the GP from scratch every time new observations arrive, which should make the results much more consistent.
=> Improve consistency of GPyModel fitting, add tests

elfi/methods/methods.py, tests/functional/test_inference.py
Added inline documentation to `methods.py` and did some light refactoring to `Rejection`.
=> Docs and refactoring

CONTRIBUTING.rst, README.md, docs/installation.rst, docs/readme.rst, docs/usage.rst, examples/ma2.py, requirements-dev.txt, requirements.txt, setup.py
Updated instructions for install. Updated some details in docs.
=> Updated installation instructions and other details in the docs

elfi/methods/methods.py, elfi/model/elfi_model.py, elfi/plotting.py
```
m = ma2.get_model()
vis = dict(xlim=[-2,2], ylim=[-1,1])
r = elfi.Rejection(m, 'd')
s = r.sample(1000, threshold=.15, vis=vis)
```
=> Interactive plotting

elfi/executor.py, elfi/store.py, tests/conftest.py, tests/functional/test_inference.py, tests/functional/test_simulation_reuse.py, tests/unit/test_store.py
Executor will now only execute those nodes that are required for the output.
=> Reusing simulations in the pool

elfi/client.py, elfi/executor.py, elfi/methods/methods.py, elfi/store.py, tests/unit/test_store.py
Addresses found issues with the pool
=> Pool improvements

elfi/__init__.py, elfi/client.py, elfi/clients/ipyparallel.py, elfi/clients/native.py, elfi/methods/methods.py, elfi/model/elfi_model.py, tests/conftest.py
Fixes the 'No key' error on `client.get`
=> Added a check for max_parallel_batches

elfi/compiler.py, elfi/graphical_model.py, elfi/model/elfi_model.py, elfi/utils.py, tests/unit/test_elfi_model.py, tests/unit/test_methods.py
- ElfiModel.parameters is now a dynamic property instead of a list
=> Fixes a bug in `NodeReference.become`.

elfi/methods/methods.py, elfi/model/elfi_model.py
=> Random seed for a new inference instance

elfi/mcmc.py, elfi/results/result.py
Fix copy&paste error in acceptance ratio :)
Fix posterior means for SMC
Make summary and posterior means properties
=> Fix mcmc smc

CHANGELOG.md, MANIFEST.in, README.md, setup.py
0.5 ready for PyPI, will become new `master` as well
=> Update changelog, prepare for 0.5

elfi/examples/__init__.py, elfi/examples/ricker.py
A simple example model using the Ricker model.
=> Ricker model

elfi/examples/__init__.py, elfi/examples/gauss.py
A model for the inference examples (e.g. rejection, BOLFI).
An introductory step to the rationale of ELFI.
Make a request for the corresponding Jupyter notebook. The notebook is used to run the examples.
N/A
A successful inference in the rejection and BOLFI methods.
The documentation corresponds to another example, ma2.py.
N/A
=> Implementing an example of the Gaussian noise model.

elfi/examples/gauss.py, tests/unit/test_examples.py
True mean value was outside prior...
=> Fix too narrow prior, add simple tests for Gauss and Ricker

elfi/methods/utils.py
- Add ability to change the stepsize
- Add ability to specify the stepsizes per dimension basis
- Removed warnings from -inf resulting from negative logpdf
=> Numeric gradient improvements

elfi/methods/bo/acquisition.py, tests/unit/test_bo.py
Noise in BO/Acquisition taken from truncated normal distribution, if the cov matrix is diagonal.
=> Change acquisition noise to truncnorm if the cov matrix is diagonal.

elfi/clients/multiprocessing.py, tests/conftest.py, tests/functional/test_randomness.py
Parallelization using the built-in multiprocessing module, which should be easier to use locally than ipyparallel.
=> Implement multiprocessing client

elfi/executor.py, elfi/methods/parameter_inference.py, elfi/methods/results.py, elfi/model/tools.py, elfi/model/utils.py, elfi/utils.py, tests/functional/test_consistency.py, tests/functional/test_custom_outputs.py
Allows also other types beside dicts.
=> Allow dicts as outputs

CHANGELOG.rst, elfi/methods/bo/acquisition.py, elfi/methods/bo/gpy_regression.py, elfi/methods/mcmc.py, elfi/methods/parameter_inference.py, elfi/methods/posteriors.py, elfi/visualization/interactive.py, tests/unit/test_bo.py
Miscellaneous fixes that occurred while updating notebooks.
=> Misc fixes

elfi/methods/mcmc.py, elfi/methods/parameter_inference.py
* more informative error messages
* allow giving initial stepsize as keyword
* each trial decreases the first stepsize to try with
=> Refine NUTS setting initial stepsize

docs/api.rst, elfi/model/elfi_model.py, elfi/model/graphical_model.py, tests/functional/test_post_processing.py, tests/unit/test_elfi_model.py
- Update ElfiModel api. Fix the remove_node method
- Update the ElfiModel api documentation
- Fix some tests
=> Api updates

Makefile
Fixes installation issue caused by ContinuumIO/anaconda-issues#542.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Aalto University
=> Fix dev installation with conda

docs/developer/architecture.rst, elfi/methods/bo/acquisition.py, elfi/methods/bo/gpy_regression.py, elfi/methods/bo/utils.py, elfi/methods/parameter_inference.py, elfi/methods/results.py, elfi/methods/utils.py, elfi/utils.py, tests/conftest.py, tests/functional/test_consistency.py, tests/functional/test_inference.py, tests/functional/test_randomness.py, tests/unit/test_bo.py, tests/unit/test_methods.py
Adds tests for consistent results given the same seed and initial conditions. Includes quite a bit of refactoring.
=> Consistency tests

Makefile, docs/index.rst, docs/quickstart.rst, docs/usage/BOLFI.rst, docs/usage/external.rst, docs/usage/parallelization.rst, docs/usage/tutorial.rst, elfi/__init__.py, elfi/methods/parameter_inference.py
=> Updated docs

.travis.yml
=> Make Travis run on OS X as well

elfi/client.py, elfi/clients/ipyparallel.py, elfi/clients/multiprocessing.py, elfi/clients/native.py, elfi/methods/parameter_inference.py, elfi/model/elfi_model.py
- Improved logging messages
- Improved batch submission policy
- Removed unused methods from clients
- Improved docs
=> Various improvements

CHANGELOG.rst, elfi/model/elfi_model.py
Fix issue #203 causing an error when creating nodes without names in interactive Python shells.
=> Fix issue 203

elfi/methods/utils.py, elfi/model/elfi_model.py, elfi/store.py, tests/unit/test_store.py
Further refactorings to the output stores and pools
=> Further pool improvements

CHANGELOG.rst, elfi/store.py, tests/functional/test_randomness.py, tests/functional/test_simulation_reuse.py, tests/unit/test_store.py
Few more fixes and improvement to arraystores, please see the CHANGELOG for details.
=> Arraystore improvements and fixes

CHANGELOG.rst, docs/installation.rst, elfi/methods/parameter_inference.py, elfi/methods/results.py, elfi/visualization/visualization.py, scripts/MA2_run.py, tests/unit/test_methods.py
Small refactorings mainly in result summaries and plotting to prepare for version 0.6.1
=> Prepare version 0.6.1

CHANGELOG.rst, Makefile, README.md, docs/quickstart.rst, docs/usage/BOLFI.rst, docs/usage/external.rst, docs/usage/parallelization.rst, docs/usage/tutorial.rst, elfi/__init__.py
Update the documentation for version 0.6.1. The changes are mainly from rerunning the notebooks, although some manual changes have been made. 
Read the new docs from here: http://elfi.readthedocs.io/en/docs_proposals/
=> Notebook doc updates

elfi/examples/bignk.py, elfi/examples/gnk.py, tests/unit/test_examples.py
The implementations of the uni- and bi-variate g-and-k models.
Increase ELFI's example's pool:
- The g-and-k models can be treated as a benchmark to test ABC methods;
- The bivariate implementation provides intuition in using ELFI for multi-dimensional data;
- The bivariate implementation infers 9 parameter values.
Run the models with the default settings.
N/A
N/A
Numpy docstring
The default settings are based on the settings described in the referred papers.
- …
=> Implementing the g-and-k models (uni- and bi-variate).

CHANGELOG.rst, elfi/examples/bignk.py, elfi/methods/parameter_inference.py, elfi/methods/utils.py, tests/unit/test_methods.py, tests/unit/test_utils.py
SMC-ABC checks that proposed parameter values are allowed by the priors.
Fixes #102
=> SMC uses ModelPrior, ensure validity of proposals

CHANGELOG.rst, Makefile, README.md, docs/quickstart.rst, docs/usage/BOLFI.rst, docs/usage/external.rst, docs/usage/parallelization.rst, docs/usage/tutorial.rst, elfi/__init__.py
=> Bump version and notebooks to 0.6.2

elfi/store.py
Makes it faster to read large amounts of data form Array pools.
- You have updated the CHANGELOG.rst (this applies to an erlier item in the list)
=> Cache memmap in npyarray

CHANGELOG.rst, elfi/client.py, elfi/executor.py, elfi/loader.py, elfi/model/elfi_model.py, elfi/store.py, elfi/utils.py, tests/functional/test_randomness.py
=> Optimize node execution order

CHANGELOG.rst, elfi/examples/bignk.py, elfi/examples/gauss.py, elfi/examples/gnk.py, elfi/methods/post_processing.py, tests/conftest.py, tests/functional/test_post_processing.py, tests/unit/test_examples.py
- Added the general Gaussian noise model;
- Improved the batch and dimensionality seperation in the summary statistics data structure (the gnk-like models).
=> [MaxVar split, Part 1] Added the general Gaussian noise model.

CHANGELOG.rst, elfi/examples/bignk.py, elfi/examples/gauss.py, elfi/examples/gnk.py
- Improved the g-and-k and Gaussian example models' documentation: aligned naming convention, expanded in the summary statistics's descriptions
=> Improved the g-and-k and Gaussian example models' documentation

CHANGELOG.rst, elfi/__init__.py, elfi/examples/lotka_volterra.py, elfi/methods/bo/utils.py, elfi/visualization/visualization.py, tests/unit/test_examples.py
New example: the stochastic Lotka-Volterra model
+ fix bounds in methods.bo.utils.minimize and shape in visualization.plot_marginals
=> Lotka-Volterra

CHANGELOG.rst, elfi/methods/diagnostics.py, tests/unit/test_diagnostics.py
- Implemented the Two Stage Procedure, a method of summary-statistics diagnostics
=> Implemented the Two Stage Procedure.

CHANGELOG.rst, elfi/methods/bo/acquisition.py, tests/conftest.py, tests/unit/test_bo.py
- Added the RandMaxVar acquisition.
=> [MaxVar split, Part 4] Added the RandMaxVar acquisition.

CHANGELOG.rst, elfi/methods/bo/acquisition.py, elfi/methods/bo/gpy_regression.py, elfi/methods/bo/utils.py, tests/conftest.py, tests/unit/test_bo.py
- Added the MaxVar acquisition.
- Added the respective tests.
=> [MaxVar split, Part 3] Added the MaxVar acquisition.

CHANGELOG.rst, elfi/methods/bo/acquisition.py, tests/conftest.py, tests/unit/test_bo.py
- Added the ExpIntVar acquisition
=> [Acquisition functions, Part 5] Added the ExpIntVar acquisition.

CHANGELOG.rst, README.md, docs/api.rst, docs/conf.py, docs/usage/external.rst, docs/usage/parallelization.rst, elfi/__init__.py, elfi/methods/diagnostics.py
=> Release 0.7

CHANGELOG.rst, README.md, docs/api.rst, docs/conf.py, docs/usage/external.rst, docs/usage/parallelization.rst, elfi/__init__.py, elfi/examples/bignk.py, elfi/examples/gauss.py, elfi/examples/gnk.py, elfi/examples/lotka_volterra.py, elfi/methods/bo/acquisition.py, elfi/methods/bo/gpy_regression.py, elfi/methods/bo/utils.py, elfi/methods/diagnostics.py, elfi/model/elfi_model.py, elfi/visualization/visualization.py, tests/conftest.py, tests/unit/test_bo.py, tests/unit/test_diagnostics.py, tests/unit/test_examples.py
=> Release 0.7 to master

docs/faq.rst, docs/usage/tutorial.rst
- Some clarifications in tutorial
- Explain vectorization in FAQ
=> Some updates in Docs

docs/faq.rst, elfi/methods/parameter_inference.py, tests/functional/test_post_processing.py
Change the default batch_size to 1, which should be easier for new users and is arguably less arbitrary than the previous default 1000.
=> Simpler default: batch_size=1

CHANGELOG.rst, README.md, docs/api.rst, docs/index.rst, elfi/__init__.py, elfi/methods/model_selection.py, tests/unit/test_model_selection.py
Implemented a simple method for model comparison.
=> Implemented model comparison.

.travis.yml, CHANGELOG.rst, README.md, docs/api.rst, docs/faq.rst, docs/index.rst, docs/usage/tutorial.rst, elfi/__init__.py, elfi/methods/model_selection.py, elfi/methods/parameter_inference.py, elfi/model/tools.py, elfi/store.py, tests/functional/test_consistency.py, tests/functional/test_post_processing.py, tests/unit/test_model_selection.py
Changelog:
- Implemented model selection (elfi.compare_models). See API documentation.
- Fix threshold=0 in rejection sampling
- Set default batch_size to 1 in ParameterInference base class
=> Release 0.7.1

README.md, docs/index.rst, docs/usage/parallelization.rst, docs/usage/tutorial.rst
Updates to docs from notebooks, arXiv
=> Docs update

CHANGELOG.rst, elfi/examples/daycare.py, elfi/examples/lotka_volterra.py, tests/unit/test_examples.py
Example of inference of transmission dynamics of bacteria in day care centers.
Treatment roughly follows:
Numminen, E., Cheng, L., Gyllenberg, M. and Corander, J.: Estimating the transmission dynamics
of Streptococcus pneumoniae from strain prevalence data, Biometrics, 69, 748-757, 2013.
=> New example: bacteria in daycare centers

.dockerignore, Dockerfile, README.md, docs/installation.rst
Added a simple Dockerfile for running ELFI as a Docker container. Update installation instructions accordingly.
=> Add Dockerfile

Makefile, requirements-dev.txt
We have a bunch of stochastic tests which sometimes fail. This PR causes failed tests to be rerun once more.
=> 'make test' reruns failed tests once.

CHANGELOG.rst, README.md, docs/usage/tutorial.rst, elfi/__init__.py
=> Bump version to 0.7.2, make docs

.dockerignore, CHANGELOG.rst, Dockerfile, Makefile, README.md, docs/index.rst, docs/installation.rst, docs/usage/parallelization.rst, docs/usage/tutorial.rst, elfi/__init__.py, elfi/client.py, elfi/clients/ipyparallel.py, elfi/clients/multiprocessing.py, elfi/clients/native.py, elfi/examples/daycare.py, elfi/examples/lorenz.py, elfi/examples/lotka_volterra.py, requirements-dev.txt, tests/unit/test_client.py, tests/unit/test_examples.py
Changelog:
- Added support for kwargs in elfi.set_client
- Added new example: inference of transmission dynamics of bacteria in daycare centers
- Added new example: Lorenz model
=> Release 0.7.2

CHANGELOG.rst, elfi/visualization/visualization.py
In case when there is need to plot 1-D Gaussian distribution using plot_pairs function from `visualization.py` module, elfi crashes. This PR fixes this bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elfi-dev/elfi/278)
=> Fix bug with plotting pairs for 1-D

CHANGELOG.rst, elfi/methods/results.py, elfi/visualization/visualization.py, tests/conftest.py, tests/unit/test_results.py
Fix bugs with processing multivariate distributions in summary, plot_pairs and plot_marginals in Sample class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elfi-dev/elfi/280)
=> Fix processing multivariate distributions

CHANGELOG.rst, elfi/visualization/visualization.py
ELFI crashes (dev branch) after trying to plot traces in BOLFI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elfi-dev/elfi/283)
=> Fix bug with shared axes

.dockerignore, Dockerfile, README.md, docs/installation.rst
Modified Dockerfile to be more suitable for running tests.
=> Improve Dockerfile for testing

CHANGELOG.rst, elfi/__init__.py, elfi/model/elfi_model.py, elfi/visualization/visualization.py
Implement `elfi.plot_some()` for plotting parameters vs. node output
=> Plotting parameters vs. node output

CHANGELOG.rst, README.md, docs/api.rst, docs/quickstart.rst, docs/usage/BOLFI.rst, docs/usage/external.rst, docs/usage/parallelization.rst, docs/usage/tutorial.rst, elfi/__init__.py
=> Preparing version v. 0.7.3

.dockerignore, .travis.yml, CHANGELOG.rst, Dockerfile, README.md, docs/api.rst, docs/installation.rst, docs/quickstart.rst, docs/usage/BOLFI.rst, docs/usage/external.rst, docs/usage/parallelization.rst, docs/usage/tutorial.rst, elfi/__init__.py, elfi/methods/parameter_inference.py, elfi/methods/post_processing.py, elfi/methods/results.py, elfi/methods/utils.py, elfi/model/elfi_model.py, elfi/visualization/visualization.py, tests/conftest.py, tests/functional/test_inference.py, tests/unit/test_bo.py, tests/unit/test_client.py, tests/unit/test_examples.py, tests/unit/test_mcmc.py, tests/unit/test_model_selection.py, tests/unit/test_results.py, tests/unit/test_utils.py
- Fix bug in plot_pairs which crashes in case of 1 parameter
- Fix bug in plot_marginals which outputs empty plots in case where we have parameter more than 5
- Fix crashing summary and plots for samples with multivariate priors
- Add progress bar for inference methods
- Add method save to Sample objects
- Add support for giving seed to `generate`
- Implement elfi.plot_params_vs_node for plotting parameters vs. node output
=> Release v. 0.7.3

setup.py
Just updating description in setup.py to match PyPI
=> Update description in setup.py

README.md, docs/index.rst
=> Update reference to JMLR

Dockerfile, Makefile, README.md, docs/installation.rst
Improve behaviour with Docker. New commands added in Makefile that facilitate building and running the container.
=> Dockerfile

.travis.yml, requirements-dev.txt
"Fixes" tests on Travis by enabling ipyparallel on Linux only.
=> Fix travis

CHANGELOG.rst, elfi/methods/parameter_inference.py, elfi/visualization/visualization.py
Fixed bug in `plot_discrepancy` function in case when one uses more than 6 parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elfi-dev/elfi/300)
=> Fix bug in plot_discrepancy for more than 6 parameters

CHANGELOG.rst, README.md, elfi/__init__.py
=> Bump version

.travis.yml, CHANGELOG.rst, Dockerfile, Makefile, README.md, docs/index.rst, docs/installation.rst, elfi/__init__.py, elfi/examples/daycare.py, elfi/loader.py, elfi/methods/mcmc.py, elfi/methods/parameter_inference.py, elfi/visualization/visualization.py, requirements-dev.txt, setup.py, tests/unit/test_bo.py, tests/unit/test_methods.py
=> Update 0.7.3 -> 0.7.4

CHANGELOG.rst, elfi/methods/parameter_inference.py, elfi/visualization/visualization.py
Improved the appearance of figures produced by `plot_gp` by removing redundant plots, rescaling the axis and added the option to draw true parameter indicators on the subplots using the optional input `true_params`.
=> Improved plot_gp

CHANGELOG.rst, CONTRIBUTING.rst, Makefile, elfi/examples/daycare.py, elfi/examples/lorenz.py, elfi/examples/lotka_volterra.py, elfi/methods/bo/acquisition.py, elfi/methods/mcmc.py, elfi/methods/parameter_inference.py, elfi/methods/utils.py, elfi/model/elfi_model.py, elfi/visualization/visualization.py, requirements-dev.txt
This PR introduces some refactoring that make ELFI better compliant to [Flake8 rules](https://lintlyci.github.io/Flake8Rules/), namely resolving [E226](https://lintlyci.github.io/Flake8Rules/rules/E226.html), [E303](https://lintlyci.github.io/Flake8Rules/rules/E303.html) and [W504](https://lintlyci.github.io/Flake8Rules/rules/W504.html) warnings that were triggered by running `make lint`.
Also, calls to `py.test` were replaced with `pytest` to future-proof (the former might become deprecated; see [this SO page](https://stackoverflow.com/a/41893170/1169233) for more info).
The CHANGELOG was updated to mention these changes; line breaks were introduced and whitespace was removed in that same file to conform it to [doc8](https://pypi.org/project/doc8/). CONTRIBUTING.rst had minor changes for …
=> Conforming to flake8 and doc8 rules + expanded CONTRIBUTING.rst

CHANGELOG.rst, CONTRIBUTING.rst, README.md
Just a few minor adjustments I found while reading the documentation. Links to files were provided and inline code has been properly formatted.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): @wleoncio 
=> Minor improvements to documentation

CHANGELOG.rst, elfi/methods/bo/utils.py, elfi/methods/parameter_inference.py
Fixed an incompatibility with scipy>=1.5 method `differential_evolution` and the output-format of the predicted mean of GPy-target_model 
=> Fix stochastic optimization

CHANGELOG.rst, elfi/methods/bo/acquisition.py, elfi/methods/post_processing.py
Improve and fix docstrings in elfi.methods.bo.acquisition and elfi.methods.post_processing
=> Fix documentation

CHANGELOG.rst, elfi/methods/parameter_inference.py, elfi/visualization/visualization.py
Modify progress bar functionality to accomodate roundwise reporting of ABC-SMC inference
=> Modify progressbar

.gitignore, CHANGELOG.rst, elfi/clients/dask.py, requirements.txt, tests/conftest.py
=> Add dask client

CHANGELOG.rst, CONTRIBUTING.rst, README.md, docs/installation.rst, docs/quickstart.rst
Update docs to include python 3.6 as the default
=> Update docs to default py36

.travis.yml, CHANGELOG.rst, elfi/methods/parameter_inference.py, elfi/methods/utils.py
This contribution fixes two small issues:
- ABC-SMC did not work in 1-dimensional parameter estimation problem due to mismatched dimensions in GM distribution class function rvs
- ABC-SMC did not return other than additional outputs in case additional outputs were requested. This behaviour did not match the method description or how additional outputs work in rejection sampler
Here's an example where the issues can be observed:
```python
import numpy as np
import scipy.stats as ss
import elfi
```
```python
def simulator(mu, batch_size=1, random_state=None):
batches_mu = np.asarray(mu).reshape((-1,1))
obs_1 = ss.norm.rvs(loc=batches_mu, scale=0.1, random_state=random_state).reshape((-1,1))
obs_2 = ss.norm.rvs(loc=1, scale=1, size=batch_size, random_state=random_state).reshape((-1,1)) …
```
=> Fix small issues in ABC-SMC

CHANGELOG.rst, README.md, docs/api.rst, docs/index.rst, elfi/methods/parameter_inference.py, elfi/model/elfi_model.py, tests/functional/test_consistency.py, tests/functional/test_inference.py, tests/unit/test_elfi_model.py
Add SMC-ABC where summary statistics are normalised to vary on similar scales. Here the scales are estimated as standard deviation under the current proposal distribution, and the normalisation is updated between SMC-ABC iterations.
Prangle D (2017). Adapting the ABC Distance Function. Bayesian Analysis 12(1):289-309, 2017. https://projecteuclid.org/euclid.ba/1460641065 (Algorithm 5)
- add an adaptive distance node class in ELFI model
- update rejection sampler to collect adaptation data and recalculate distances when used with an adaptive distance node
- nested acceptance: update rejection sampler to handle several concurrent distance functions and thresholds
- add the adaptive distance SMC-ABC sampler in inference methods
If your contribution adds, removes or somehow changes the …
=> Add adaptive distance SMC-ABC

CHANGELOG.rst, README.md
Add mention of ROMC to README.md and to CHANGELOG.rst as well. 
=> Add romc to readme.md

CHANGELOG.rst, elfi/methods/bo/acquisition.py
Add constraints to ExpIntVar so that no queries will be selected outside prior support.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): 
@hpesonen 
=> Add constaints to exp int var

README.md
Add a note with a link of adaptive ABC-SMC to README.md
=> Add aABCSMC to README.md

elfi/methods/bo/acquisition.py, elfi/methods/parameter_inference.py
=> Fix linting.

CHANGELOG.rst, elfi/methods/mcmc.py, elfi/methods/parameter_inference.py, tests/unit/test_mcmc.py
Rename `gelman_rubin` to `gelman_rubin_statistic` to increase the informativity of the function name. 
=> Rename gelman_rubin to gelman_rubin_statistic

.github/PULL_REQUEST_TEMPLATE.md
Modified PULL_REQUEST_TEMPLATE.md by removing the tickbox: "The proposed changes pass all unit tests (check step 6 of CONTRIBUTING.rst for details)"  as I feel it's redundant _as a tick box_ due to unit tests needing to be passed anyways before merging. 
=> Modify PULL_REQUEST_TEMPLATE.md

CHANGELOG.rst, elfi/methods/density_ratio_estimation.py, elfi/methods/inference/samplers.py, tests/functional/test_inference.py, tests/unit/test_methods.py
Adaptive threshold ABC-SMC implementation as a separate method. Previous version included adaptive-quantile-based threshold adaptation as an option in ABC-SMC.
- new class: `AdaptiveThresholdSMC`
=> Separate adaptive threshold ABC-SMC and ABC-SMC

elfi/methods/results.py
=> Fix typos and remove outcommented code.

elfi/methods/inference/samplers.py
Refactored samplers.py and removed duplicate code.
=> Refactor ABC-SMC-methods.

elfi/methods/inference/samplers.py
=> Fix a minor bug in AdaptiveThresholdSMC

elfi/methods/inference/samplers.py
Change KLIEP basis sigma from maximum of marginals to minimum of marginals. 
=> Base KLIEP basis sigma on minimum marginal sigma

.readthedocs.yml
update .readthedocs.yml with python 3.6
=> Update readthedocs configuration file

elfi/methods/mcmc.py
=> Minor docstring fixes in mcmc.nuts

CHANGELOG.rst, elfi/visualization/visualization.py
Improve the visual outlook of `plot_gp`, `plot_pairs`, `plot_traces`, `plot_marginals`, ...
=> Fix plot gp ratios

CHANGELOG.rst, elfi/visualization/visualization.py
Fixed a bug where plot_traces() crashed if only one chain was simulated.
=> Fix plot traces

.github/workflows/pytest.yml, CHANGELOG.rst
Due to the unavailability of travis-ci free CI-plan, we'll implement CI via github actions.
=> Implement CI workflow using GitHub actions

.github/workflows/pytest.yml, CHANGELOG.rst, CONTRIBUTING.rst
Fixed a couple of errors in the CONTRIBUTING.rst and added instructions for syncing the fork from upsteam base before making a pull request.
=> Modify CONTRIBUTING.rst

CHANGELOG.rst, README.md
Fixed build status badge on README.md and removed obsolete landscape.io badge
=> Fix build badge

CHANGELOG.rst, elfi/examples/lotka_volterra.py
The provided true parameters were out of the provided prior distributions. The prior distributions have been changed to follow the ones in the given reference.
=> Fix lotkavolterra

CHANGELOG.rst, README.md, docs/conf.py, elfi/__init__.py
=> Prepare v0.8.3

CHANGELOG.rst, elfi/methods/inference/bolfire.py, elfi/utils.py
Included dimension check in `is_array` in `utils`. Previous version assumed that a variable behaves like a numpy array when it has a shape attribute. This meant that variables like `param=params[0]` where `params` is a numpy array would be considered numpy arrays while commands like `len(param)` and `param[0]` do not work in this case. This caused errors in `run_vectorized` which checks whether `inpt` is an array and then proceeds to call `len(inpt)` (L46-47) and had to be addressed with float conversion in BOLFIRE.
Here is an example where the issue can be observed:
```python
import numpy as np
import scipy.stats as ss
import elfi
```
```python
m=elfi.new_model()
t1=elfi.Prior('uniform',0,1)
t2=elfi.Prior('uniform',0,1)
simulate = lambda t1, t2, random_state: …
```
=> Fix array check

CHANGELOG.rst, elfi/examples/arch.py
Add details to ARCH(1)-model docstring
=> Add arch description

CHANGELOG.rst, elfi/examples/lotka_volterra.py
=> Add option to disable observation noise from lotka-volterra.

CHANGELOG.rst, elfi/examples/lotka_volterra.py
Add summary statistic to lotka-volterra model
@hpesonen 
=> Add sumstats to lv

CHANGELOG.rst, elfi/examples/arch.py, elfi/examples/lotka_volterra.py
arch.py docstring caused a linting error. this has been fixed. 
@hpesonen 
=> Fix lint in arch

elfi/methods/inference/bolfi.py, elfi/methods/results.py
=> Fix linting

CHANGELOG.rst, README.md, elfi/__init__.py
=> Bump to version 0.8.4

CHANGELOG.rst, elfi/classifiers/classifier.py, tests/functional/test_classifiers.py
Added Gaussian process classifier for ratio estimation. The ratio estimation classifiers are used in BOLFIRE.
=> Add Gaussian process classifier

CHANGELOG.rst, elfi/examples/scratch_assay.py, tests/unit/test_examples.py
Add the model proposed by [Johnston et al (2014)](https://doi.org/10.1098/rsob.140097) to simulate cell behaviour in scratch assay experiment, and an example ELFI model that uses the simulation model with the summaries proposed by [Price et al (2018)](https://doi.org/10.1080/10618600.2017.1302882).
- Code: BSD3 …
=> Add scratch assay example

CHANGELOG.rst, elfi/examples/scratch_assay.py
- fix how observations are initialised so that full arrays are observed
- fix `pp` prior distribution to match the cited works
=> Fix scratch assay example

CHANGELOG.rst, elfi/examples/mg1.py
this update fixes the simulator model used in M/G/1 example and updates the inference task created with `get_model` to better match previous works.
about the simulator model: `MG1` assumed that parameter vectors have `batch_size` identical values and simulated all `batch_size` observation sequences with the same parameter values. i fixed this because ELFI batches are not constrained to repeat the same parameter value. in addition there was an error in interdeparture time calculation. the interdeparture times depend on `sum_w` = current client arrival time and `sum_x` = previous client departure time which both had an index error in the update rule.
about updates in `get_model`: the minimum service time `t1` was associated with a uniform prior between zero and the observed minimum …
=> Fix M/G/1 example

CHANGELOG.rst, elfi/examples/toad.py
this update substitutes the sequential batch simulation in `batch_toad` with array operations and adds support for batches that have `batch_size` different parameter values. `batch_toad` and `toad` are also combined into `toad`, and summary calculation is broken into four nodes that represent summaries calculated at each `lag = 1, 2, 4, 8`. the update on summary calculation is cosmetic and was done with the lotka-volterra and arch examples in mind, ie to match how summaries are represented in those ones.
- the old and new `toad(1.5, 35, 0.5)` should take around the same time while the new `toad(1.5, 35, 0.5, batch_size=100)` should run much faster than the old `toad_batch(1.5, 35, 0.5, batch_size=100)`. the difference was around 5 seconds vs 250 ms on my laptop, measured with timeit in …
=> Faster batch simulations in toad model

CHANGELOG.rst, elfi/examples/stochastic_volatility_model.py
this update fixes the simulator model used in stochastic volatility example and introduces some updates in the inference task created with `get_model`.
about the simulator: 
update adds exp and square root transformation so that log-returns are calculated as `np.exp(0.5 * x_t) * v_t` as proposed in previous works, and also updates log-volatilities initialisation. the previous version sampled x(0) from `ss.norm.rvs(mu + phi * (- mu), sigma)`, which corresponds to assuming that x(-1) = 0. this initialisation option is still available in the current version, ie the user can provide a previous x value and can choose to provide zero, but the default initialisation now uses the equilibrium distribution `ss.norm.rvs(mu, sigma/np.sqrt(1 - phi**2))` as proposed in [vankov et al …
=> Fix stochastic volatility example

CHANGELOG.rst, elfi/methods/inference/bolfire.py
update BOLFIRE parent class to model-based parameter inference and let the parent class handle data collection
=> BOLFIRE parent class update

CHANGELOG.rst, elfi/examples/ar1.py
Fix a couple of minor bugs in ar1
=> Fix a couple of minor bugs in ar1.

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.rst
Modified this template as I find the checklist bullet clicking irrelevant. 
=> Modify pr template

CHANGELOG.rst, docs/conf.py
Add new mocked modules for RTD build
Please list the copyright holder for the work you are submitting (this will be you or …
=> Update rtd-configuration with new mocked modules

CHANGELOG.rst, docs/conf.py
Add more bsl-related mocked modules.
Please list the copyright holder for the work you are submitting (this will be you or …
=> Add mocked modules

CHANGELOG.rst, elfi/examples/bignk.py, elfi/examples/daycare.py, elfi/methods/inference/bolfi.py, elfi/methods/inference/romc.py, elfi/methods/posteriors.py, elfi/model/extensions.py, requirements.txt, tests/functional/test_inference.py, tests/unit/test_examples.py, tests/unit/test_utils.py
in response to #444 update codebase to work with numpy 1.24 and remove constraint on numpy version. closes #447
Please …
=> Update numpy version

CHANGELOG.rst, README.md, elfi/__init__.py
Update broken 0.8.5
Please list the copyright holder for the work you are submitting (this will be you or your assignee, …
=> Prepare version v.0.8.6

CHANGELOG.rst, README.md, elfi/__init__.py
Bump version number
Please list the copyright holder for the work you are submitting (this will be you or your assignee, …
=> Prepare v087
