elfi-dev/elfi

- elfi/graph.py
- tests/unit/test_core.py
When user tries to add a node with a pre-existing name, a SystemExit is raised and the user is given suggestions on what to do.
Raise exception with message and short traceback.
Try to create a node with a pre-existing name.
None.
Not applicable.
> Add node raises more user-friendly exception

- elfi/env.py
Set tornado's logLevel to warning.
Nicer terminal output.
The appearance of INFO messages appeared somewhat inconsistent, so nontrivial.
-
-
> Set tornado's logLevel to warning.

- elfi/storage.py
> Remove lambda from LocalElfiStore to enable serialization

- elfi/graphical_model.py
- elfi/model/elfi_model.py
- examples/ma2.py
- tests/conftest.py
- tests/functional/test_inference.py
- tests/unit/test_elfi_model.py
Before:
`t1 = Prior('t1', ...)`
Now:
`t1 = Prior(..., name='t1')`
Or
`t1 = Prior(...)`
In the last case the name is inferred automatically with `inspect`
> Changed the node naming ui

- elfi/bo/gpy_regression.py
- elfi/methods/methods.py
- elfi/model/elfi_model.py
- examples/ma2.py
- tests/unit/test_examples.py
All outputs are required to be arrays. Make the default output of `Prior` a 1d vector. Do not require any longer that all vectors need to be at least 2d. Strip away unnecessary dimensions if possible to follow numpy convention.
> Node output size refactoring

- elfi/client.py
- elfi/compiler.py
- elfi/loader.py
- elfi/model/elfi_model.py
- tests/functional/test_compilation.py
- tests/functional/test_serialization.py
- tests/unit/test_elfi_model.py
Allows node to receive the `batch_index` as a parameter for the node operation.
Example
------------
```
sim = elfi.Simulator(...)
sim['_uses_batch_index'] = True
```
> Support for batch_index parameter to nodes

- elfi/results/result.py
- tests/unit/test_results.py
Result object raises KeyError when non-existent item requested
Add some tests for Result
> Raise AttributeError when non-existent item requested, add tests

- elfi/utils.py
Tested ELFI dev (and bolfi_seed)  in Windows 10:
- tests: native + ipyparallel
- notebooks: tutorial + parallelization
- too much hazzle now to set up the system for the external operations
Everything works fine after this small change.
> Unsigned int32 doesn't seem to work in Windows 10: changed to signed

- elfi/methods/parameter_inference.py
- tests/functional/test_inference.py
- tests/unit/test_bo.py
- tests/unit/test_methods.py
Bounds must be given as dict for BO/BOLFI. This ensures that their order stays the same as for model parameters.
> Bounds must be given as dict for BO/BOLFI

- tests/functional/test_simulation_reuse.py
This test failed too often because of a too strict time limit.
> Loosen a too tight time limit

- docs/api.rst
- elfi/__init__.py
- elfi/methods/post_processing.py
- requirements.txt
- tests/functional/test_post_processing.py
Adds post processing for results obtained from other ABC algorithms.
I added two regression test that check the results are the same as
[here](https://github.com/kskyten/elfi-notebooks/blob/regression_adjustment/ELFI_regression_adjustment.ipynb). The tests pass locally, but I'm not sure how to get them working on travis as they depend on the bdm binary in the examples.
See this [notebook](https://github.com/kskyten/elfi-notebooks/blob/regression_adjustment/ELFI_regression_adjustment.ipynb).
> Add linear regression adjustment

- elfi/methods/bo/acquisition.py
- elfi/methods/bo/utils.py
- elfi/methods/posteriors.py
- tests/functional/test_inference.py
- tests/unit/test_utils.py
As the argument is not a strict functional requirement for
using the minimization interface, it should be optional to
allow better using minimize() as a general functionality.
> Make gradient function argument optional in minimize

- elfi/methods/bo/gpy_regression.py
- elfi/methods/parameter_inference.py
- tests/unit/test_bo.py
Previously BOLFI required a certain number of initial samples
to be computed. As this is not a strict functional requirement,
remove this strict restriction and make it a recommendation instead.
User will receive a warning if the number of initial samples is
not large enough based on initial analysis of the situation.
> Make initial samples requirement a recommendation instead

- elfi/methods/parameter_inference.py
- tests/unit/test_bo.py
Allow a mode that loosens the requirement for the exactly same results for the same initial conditions, but can allow a more efficient use of computation resources in parallel settings. This PR returns the possibilty for the earlier default behaviour.
> Async mode for BOLFI

- CHANGELOG.rst
- elfi/client.py
- tests/conftest.py
Allows changing the client with strings
```
elfi.set_client('ipyparallel')
```
> Easier client switching

- CHANGELOG.rst
- docs/api.rst
- elfi/model/elfi_model.py
- tests/unit/test_elfi_model.py
Allows saving the `ElfiModel` with `model.save()`. Loading can be done with either `elfi.load_model` or `ElfiModel.load`.
> Easier model saving and loading

- CHANGELOG.rst
- elfi/loader.py
- elfi/methods/parameter_inference.py
- elfi/methods/utils.py
- elfi/model/elfi_model.py
- elfi/model/tools.py
- elfi/utils.py
- tests/functional/test_randomness.py
Reduces the time to generate sub seeds. With very large `OutputPool`s the sub seed generation took too much time when rerunning the inference using the stored values in the pool.
> Improve sub seed generation performance

- CHANGELOG.rst
- elfi/model/elfi_model.py
Change signature and behaviour of elfi.Distance so that it works with scipy 1.0.0, which changed the signature of `scipy.spatial.distance.cdist`.
See also https://scipy.github.io/devdocs/release.1.0.0.html
> Fix elfi.Distance to support scipy 1.0.0

- .travis.yml
- tests/functional/test_consistency.py
- Fix Mac setup in Travis after changes in Homebrew.
- Relax consistency tests from `np.array_equal` to `np.allclose` to decrease the chance of random failures.
> Fix Travis

- elfi/methods/parameter_inference.py
There was a bug when setting `threshold=0` in rejection sampling.
#260
> Fix setting threshold=0

- CHANGELOG.rst
- README.md
- elfi/__init__.py
- elfi/model/tools.py
- elfi/store.py
Prepare for release 0.7.1. Its changelog will be:
0.7.1 (2018-04-11)
------------------
- Implemented model selection (elfi.compare_models). See API documentation.
- Fix threshold=0 in rejection sampling
- Set default batch_size to 1 in ParameterInference base class
> Preparing version 0.7.1 to dev

- CHANGELOG.rst
- elfi/client.py
- elfi/clients/ipyparallel.py
- elfi/clients/multiprocessing.py
- elfi/clients/native.py
- tests/unit/test_client.py
Allows e.g.
`elfi.set_client('multiprocessing', processes=2)`
`elfi.set_client('ipyparallel', sshserver='my.server.org')`
> Add support for kwargs to elfi.set_client

- elfi/methods/results.py
- elfi/visualization/visualization.py
Depending on model, in some cases progress bar might crash because of zero number of `self._objective_n_batches`. This PR prevents crashing and gives kind caution for users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elfi-dev/elfi/288)
> Fix bug with zero total number iterations in progress bar

- CHANGELOG.rst
- elfi/methods/parameter_inference.py
- elfi/utils.py
- requirements-dev.txt
- tests/conftest.py
Previously fitting bolfi required at least one new evidence point in addition to initial pre-generated evidence points
> Enable BOLFI-fit using only initial evidence points.

- CHANGELOG.rst
- elfi/methods/bo/acquisition.py
- elfi/methods/bo/utils.py
- elfi/methods/posteriors.py
- tests/functional/test_inference.py
- tests/unit/test_utils.py
This PR implements constraints for the minimizer used by BOLFI.
I've been working on a project (together with @umbertosimola and @dbarg) where we infer two parameters x and y using BOLFI. The parameter space is constrained by ``x**2 + y**2 < R**2`` for some constant R. However there was no way to call the underlying ``scipy.optimize.minimize`` routine with constraints. These changes pass the ``constraints`` argument to the minimizer from the AcquisitionBase class, allowing for the definition of an acquisition method with constraints on the parameter space.
- I haven't yet, should I just add the PR name to the top of the list?
- I've updated docstrings however ``make docs`` did not run since I don't …
> Minimizer constraints for BOLFI

- elfi/methods/parameter_inference.py
Added "-th" to clarify order notation.
> add notation to clarify how threshold param is interpreteted docstring

- .travis.yml
- CHANGELOG.rst
Include python 3.7 to Travis setup and remove python 3.5 due to clash with dask
> Update travis tests to py36

- elfi/visualization/visualization.py
ProgressBar doubleprints the final iteration. Update fixes this and the bug of progressbar exceeding 100%
> Fix ProgressBar doubleprint-bug

- docs/usage/implementing-methods.rst
Fixing bugs caused by the split of parameter_inference-module
> Fix reference to parameter_inference-module

- elfi/methods/inference/samplers.py
- tests/unit/test_elfi_model.py
`Sampler`s refer to `InferenceMethod` in docstring instead of `ParameterInference`. This has been fixed. 
> Change reference from InferenceMethod to ParameterInference.

- CHANGELOG.rst
- elfi/visualization/visualization.py
elfi.draw did not fill observable nodes with gray due to a bug.  
> Fix draw elfi-graph

- CHANGELOG.rst
- elfi/methods/inference/bolfi.py
If given precomputed data to BOLFI, it's not taken into consideration when reporting number of simulations with the posterior sample object. This has been fixed by changing the reported number from `n_sim` to `n_evidence`.
- Documentation: CC-BY 4.0 …
> Change BOLFI.Sample to report n_evidence instead of n_sim.

- CHANGELOG.rst
- elfi/visualization/visualization.py
Histograms in visualization.plot_pairs() were weirdly aligned regarding the actual samples, and this has been fixed. Also added some improvements to visual appearance of the plotting. 
> Fix histograms in plot pairs

- CHANGELOG.rst
- docs/usage/BOLFI.rst
- elfi/methods/bo/acquisition.py
- elfi/methods/bo/gpy_regression.py
- elfi/methods/inference/bolfi.py
- elfi/methods/inference/bolfire.py
- elfi/methods/inference/romc.py
- tests/unit/test_bo.py
Changed `AcquisitionBase`constructor API so that user has to explicitly assign `noise_var` to parameters. 
This is to prevent a bug where `noise_var`-elements are assigned arbitrarily to dimensions.
- Documentation: CC-BY 4.0 …
> Fix acq_noise_var API

- CHANGELOG.rst
- elfi/methods/bo/acquisition.py
- elfi/methods/inference/bolfi.py
- elfi/methods/inference/bolfire.py
- elfi/methods/utils.py
- tests/unit/test_methods.py
Earlier `sigma_proposals` to be used in `metropolis` were input as a list. To make sure that standard deviations are assigned correctly to parameter dimensions, input format has been changed from List to Dict.
- Documentation: CC-BY 4.0 …
> Require a dictionary for sigma_proposals to be fed in metropolis.

- CHANGELOG.rst
- elfi/methods/bo/acquisition.py
- elfi/methods/bo/utils.py
- elfi/methods/inference/bolfire.py
- tests/unit/test_utils.py
Added `CostFunction` class to represent acquisition costs with gradient, and introduced option to use additive costs in LCBSC. The new feature substitutes the option to add negative log-prior values to acquisition scores in LCBSC, and BOLFIRE was updated to use the new feature.
- Code: BSD3 …
> Add additive acquisition cost

- CHANGELOG.rst
- elfi/methods/inference/bolfire.py
- tests/unit/test_bolfire_unit.py
updated likelihood data generation in BOLFIRE so that it uses the batch system in ELFI. the current version in ELFI uses `model.generate` to run `n_training_data` simulations with selected parameter values. the new version updates parameter values between data collection rounds and uses the batch system to run the `n_training_data` simulations needed to complete each round. the simulations are carried out in `batch_size` batches that can be run in parallel. `n_training_data` must be a multiple of `batch_size`.
notes: 
- the current new implementation does not allow running simulations with several parameter values at the same time. this means that new parameter values are not selected and new batches are not submitted until the current parameter values have been used to run …
> Update BOLFIRE to run simulations in batches

- CHANGELOG.rst
- elfi/methods/posteriors.py
- tests/functional/test_bolfire.py
BOLFIRE posterior includes MAP estimates as an attribute that is calculated when the posterior is initialised. however the sample function for example does not need MAP estimates. this update removes the attribute and makes MAP estimation optional to the user. in addition the estimates are calculated based on the estimated log-posterior rather than estimated posterior.
By submitting this pull request, the copyright holder is agreeing to license the …
> Update BOLFIRE posterior

- CHANGELOG.rst
- elfi/model/elfi_model.py
- tests/unit/test_elfi_model.py
`outputs` is an optional input to the elfi model `generate` function, but the current version returns an error when called without `outputs`. this is because the default option is broken: `generate` tries to use `source_net.nodes` which is a nodeview instance when a list is needed. here it is converted.
i also added a new test because the current set did not cover the broken feature and it can break when `source_net` is updated. `source_net.nodes` was a list in the networkx version that was in use earlier.
Please list the copyright holder for the work you are submitting (this will be you …
> Fix generate outputs

- CHANGELOG.rst
- elfi/executor.py
simulator nodes in the ELFI model have a property called `observed` which is defined [here](https://github.com/elfi-dev/elfi/blob/dev/elfi/model/elfi_model.py#L742-L746). however the computation fails because `get_execution_order` cannot handle the case that no nodes need to be executed.
```python
import elfi.examples.ma2
model = elfi.examples.ma2.get_model()
model['MA2'].observed
```
By submitting this pull request, the copyright holder is agreeing to …
> Fix simulator node observed

- CHANGELOG.rst
- elfi/methods/inference/bolfire.py
- tests/functional/test_bolfire.py
- tests/unit/test_bolfire_unit.py
- introduce new optional input variable `feature_names`
- make `n_training_data` not optional
- update is related to issue #406 but does not solve it. problem is that the current implementation needs the feature nodes to be observable, and the operation nodes are not.
- BOLFIRE attribute `summary_names` was substituted with `feature_names` because the features used in classification can now also include the raw simulated data.
By submitting this pull …
> Update BOLFIRE inputs

- CHANGELOG.rst
- elfi/methods/inference/bolfi.py
- elfi/methods/inference/bolfire.py
- elfi/model/extensions.py
update `ModelPrior` to allow control over parameter order and update the model priors used in BOLFI and BOLFIRE to use the parameter order used in their `target_model`
- what was the problem:
BOLFI and BOLFIRE use a target model to represent dependencies between parameter vectors and a response variable. previous updates #402 and #403  addressed the issue that BOLFI and BOLFIRE converted parameter dictionaries into parameter vectors based on `self.parameter_names` which corresponds to `self.model.parameter_names`. parameters presented to the target model are now ordered based on `self.target_model.parameter_names`. however both methods also use a `ModelPrior` instance that orders parameter values based on `self.model.parameter_names`. this could be a problem because BOLFI and BOLFIRE …
> Fix parameter order in model prior

- CHANGELOG.rst
- elfi/methods/inference/bolfi.py
- update `plot_state` to calculate acquisition scores based on the same acquisition index that is used in `prepare_new_batch`.
- update `plot_state` to use `target_model.instance` so that it does not access `target_model._gp` which looks private.
- Documentation: CC-BY 4.0 …
> Fix acquisition index in state plot

- CHANGELOG.rst
- elfi/examples/lotka_volterra.py
Changed poisson priors in Lotka-Volterra-model to approximate Gaussians, because most inference methods in elfi do not support discrete priors.
> Modify lv priors

- CHANGELOG.rst
- MANIFEST.in
- README.md
- docs/usage/BOLFI.rst
- elfi/__init__.py
- elfi/examples/arch.py
- elfi/examples/lotka_volterra.py
- elfi/executor.py
- elfi/methods/bo/acquisition.py
- elfi/methods/bo/gpy_regression.py
- elfi/methods/bo/utils.py
- elfi/methods/inference/bolfi.py
- elfi/methods/inference/bolfire.py
- elfi/methods/inference/romc.py
- elfi/methods/posteriors.py
- elfi/methods/results.py
- elfi/methods/utils.py
- elfi/model/elfi_model.py
- elfi/model/extensions.py
- elfi/utils.py
- tests/functional/test_bolfire.py
- tests/unit/test_bo.py
- tests/unit/test_bolfire_unit.py
- tests/unit/test_elfi_model.py
- tests/unit/test_methods.py
- tests/unit/test_utils.py
- tox.ini
- Modify Lotka-Volterra model's priors as many methods do not support discrete random variables.
- Fix acquisition index in state plot
- Reformat `summary()` for `Sample(ParameterInferenceResult)`
- Fix linting in `arch.py`
- Add summary statistics to Lotka-Volterra model
- Add boolean `observation_noise` option to `lotka_volterra`
- Add parameter names as an optional input in model prior and fix the parameter order in priors used in BOLFI and BOLFIRE
- Add feature names as an optional input and make training data size a required input in BOLFIRE
- Fix the observed property in simulator nodes
- Fix default outputs in generate
- Add docstring description to ARCH-model
- Make MAP estimates calculation in BOLFIRE optional and based on log-posterior
- Use batch system to run simulations in …
> Release v0.8.4

- CHANGELOG.rst
- elfi/examples/daycare.py
update multidimensional indexing with a non-tuple sequence `arr[seq]` to `arr[tuple(seq)]` in the daycare example. otherwise the example does not work when tested with python 3.8. this is because the test uses numpy 1.23.0 where multidimensional indexing with non-tuple values is not allowed, see [release notes](https://numpy.org/devdocs/release/1.23.0-notes.html#expired-deprecations).
By submitting this pull request, the copyright holder is agreeing to …
> Fix daycare example

- CHANGELOG.rst
- elfi/methods/bsl/pre_sample_methods.py
- elfi/visualization/visualization.py
this update fixes the axes shape in `plot_marginals` and removes `plot_summaries`. `plot_summaries` is not needed because both visualisation methods take a sample dict as input and plot sample histograms. the main difference between the two methods was that `plot_marginals` was not able to divide plots into several rows due to the error that is fixed here.
By submitting this pull request, the copyright holder is agreeing to license the submitted work under …
> Remove plot summaries

- CHANGELOG.rst
- elfi/methods/bsl/cov_warton.py
- elfi/methods/bsl/gaussian_copula_density.py
- elfi/methods/bsl/gaussian_rank_corr.py
- elfi/methods/bsl/pdf_methods.py
- tests/functional/test_syn_likelihoods.py
this update on `semi_param_kernel_estimate` fixes the covariance to correlation matrix conversion used when `shrinkage=glasso` and updates the likelihood calculation so that warton shrinkage is used when `shrinkage=warton`. i also added tests to capture these issues and moved some computations around to make the likelihood calculation easier for me to follow.
By submitting this pull request, the copyright holder is agreeing to license the submitted work …
> BSL update semiparametric likelihood calculation

- .github/workflows/pytest.yml
- CHANGELOG.rst
- CONTRIBUTING.rst
- README.md
- docs/installation.rst
- elfi/methods/diagnostics.py
- requirements-dev.txt
- setup.py
Update test matrix by dropping support for py36 and adding py39 and py310
> Drop support for py36 and add py39 and  py310

- CHANGELOG.rst
- requirements.txt
New version of numpy broke the execution. Restrict numpy < 1.24 until codebase has been updated to work with the new version.
and the proposed changes pass all unit tests (check step 6 of CONTRIBUTING.rst for …
> Restrict numpy version

- CHANGELOG.rst
- README.md
- elfi/__init__.py
0.8.5 (2023-03-07)
------------------
- Fix the option to continue inference in model-based inference
- Move classifiers
- Fix readthedocs configuration
- Update penalty to shrinkage parameter conversion in synthetic likelihood calculation
- Update BSL pre sample methods
- Update BslSample
- Move ROMC tests
- Update to numpy 1.24
- Update readthedocs configuration
- Restrict numpy < 1.24 until codebase has been updated
- Update documentation-related files: docs, conf.py and requirements-dev.txt 
- Update PULL_REQUEST_TEMPLATE.md
- Drop tests for py36 and add tests for py39 and py310
- Fix couple of minor bugs in `ar1`-model
- Update parent class in BOLFIRE
- Fix semiparametric synthetic likelihood with glasso/warton and add tests
- Fix plot marginals and remove plot summaries
- Fix …
> Release v0.8.5

- .readthedocs.yml
- CHANGELOG.rst
- README.md
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- elfi/__init__.py
- requirements.txt
- Update available methods list
- Pin `numpy <= 1.24.0` due to `GPy`
- Update RTD configuration
> Release v0.8.7
